version: '3.8'

services:
  web:
    build: .
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-default-key}
      - ALLOWED_HOSTS=django.devci.net,localhost,127.0.0.1
      - DJANGO_SETTINGS_MODULE=api.settings
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "90:90"
    volumes:
      - static_volume:/var/www/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume: