version: '3.8'

services:
  app:
    build: .
    ports:
      - "8787:8787"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-default-key}
      - ALLOWED_HOSTS=django.devci.net,localhost,127.0.0.1
      - DJANGO_SETTINGS_MODULE=api.settings
    restart: unless-stopped